;; Load AI player components directly (no namespace to avoid switching issues)
(load-file "dev/src/clj/ai_websocket_client_v2.clj")
(load-file "dev/src/clj/ai_client.clj")
(load-file "dev/src/clj/ai_player.clj")

(println "\n🤖 AI Player Loaded!")
(println "================================")

;; Create convenient aliases in CURRENT namespace using intern
(intern *ns* 'connect! @(resolve 'ai-websocket-client-v2/connect!))
(intern *ns* 'disconnect! @(resolve 'ai-websocket-client-v2/disconnect!))
(intern *ns* 'state @(resolve 'ai-player/state))
(intern *ns* 'actions @(resolve 'ai-player/actions))
(intern *ns* 'help @(resolve 'ai-player/help))
(intern *ns* 'play @(resolve 'ai-player/play))
(intern *ns* 'run @(resolve 'ai-player/run))
(intern *ns* 'choose @(resolve 'ai-player/choose))
(intern *ns* 'do-action @(resolve 'ai-player/do-action))
(intern *ns* 'games @(resolve 'ai-websocket-client-v2/show-games))
(intern *ns* 'refresh-games @(resolve 'ai-websocket-client-v2/request-lobby-list!))
(intern *ns* 'join-game! @(resolve 'ai-websocket-client-v2/join-game!))

(println "\n✨ Functions available in" *ns* ":")
(println "  CONNECTION:")
(println "    (connect! \"ws://localhost:1042/chsk\") - Connect to server")
(println "    (disconnect!)                        - Disconnect from server")
(println "  LOBBY:")
(println "    (refresh-games)                      - Get list of games")
(println "    (games)                              - Show available games")
(println "    (join-game! {:gameid \"...\" :side \"Corp\"}) - Join a game")
(println "  IN-GAME:")
(println "    (state)                              - Show game state")
(println "    (actions)                            - Show available actions")
(println "    (play \"Card\" [\"Server\"])             - Play a card")
(println "    (run \"hq\")                            - Run on a server")
(println "    (choose \"option\")                     - Respond to prompt")
(println "    (do-action \"click-credit\")           - Basic actions")
(println "  HELP:")
(println "    (help)                               - Show full help")
